CREATE TABLE USUARIOS
(
    ID_USUARIO       NUMBER GENERATED ALWAYS AS IDENTITY,
    CEDULA           VARCHAR2(8)                  NOT NULL,
    NOMBRE           VARCHAR(50)                  NOT NULL,
    APELLIDO         VARCHAR(50)                  NOT NULL,
    ID_PERFIL        NUMBER                       NOT NULL,
    ID_INSTITUCION   NUMBER                       NOT NULL,
    EMAIL            VARCHAR2(255)                NOT NULL,
    NOMBRE_USUARIO   VARCHAR2(255)                NOT NULL,
    CONTRASENIA      VARCHAR2(255)                NOT NULL,
    ESTADO           VARCHAR(20) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_NACIMIENTO DATE,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT CEDULA UNIQUE (CEDULA),
    CONSTRAINT EMAIL UNIQUE (EMAIL)
);

CREATE TABLE INTERVENCIONES
(
    ID_INTERVENCION NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO      NUMBER       NOT NULL,
    ID_TIPO         NUMBER       NOT NULL,
    ID_EQUIPO       NUMBER       NOT NULL,
    MOTIVO          VARCHAR(255) NOT NULL,
    FECHA_HORA      DATE         NOT NULL,
    COMENTARIOS     VARCHAR(255),
    CONSTRAINT PK_INTERVENCIONES PRIMARY KEY (ID_INTERVENCION)
);

CREATE TABLE TIPOS_INTERVENCIONES
(
    ID_TIPO     NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_TIPO VARCHAR(30)                  NOT NULL,
    ESTADO      VARCHAR(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_TIPOSINTERVENCIONES PRIMARY KEY (ID_TIPO),
    CONSTRAINT UK_NOMBRETIPOINTERVENCIONES UNIQUE (NOMBRE_TIPO)
);

CREATE TABLE TIPOS_EQUIPOS
(
    ID_TIPO     NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_TIPO VARCHAR(30) NOT NULL,
    CONSTRAINT PK_TIPO PRIMARY KEY (ID_TIPO),
    CONSTRAINT UK_NOMBRETIPOSEQUIPOS UNIQUE (NOMBRE_TIPO)
);

CREATE TABLE EQUIPOS
(
    ID_EQUIPO         NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_INTERNO        VARCHAR(50)  NOT NULL,
    ID_UBICACION      NUMBER       NOT NULL,
    NRO_SERIE         VARCHAR(100) NOT NULL,
    NOMBRE            VARCHAR(100) NOT NULL,
    ID_TIPO           NUMBER       NOT NULL,
    ESTADO            VARCHAR(20) DEFAULT 'ACTIVO',
    ID_PROVEEDOR      NUMBER,
    ID_PAIS           NUMBER,
    ID_MODELO         NUMBER,
    IMAGEN            VARCHAR(255),
    FECHA_ADQUISICION DATE,
    CONSTRAINT PK_EQUIPOS PRIMARY KEY (ID_EQUIPO),
    CONSTRAINT UK_IDINTERNOEQUIPOS UNIQUE (ID_INTERNO),
    CONSTRAINT UK_NROSERIEEQUIPOS UNIQUE (NRO_SERIE)
);

CREATE TABLE PROVEEDORES_EQUIPOS
(
    ID_PROVEEDOR NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE       VARCHAR(30) NOT NULL,
    CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID_PROVEEDOR)
);

CREATE TABLE PAISES
(
    ID_PAIS NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE  VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PAISES PRIMARY KEY (ID_PAIS)
);

CREATE TABLE MODELOS_EQUIPOS
(
    ID_MODELO NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_MARCA  NUMBER      NOT NULL,
    NOMBRE    VARCHAR(50) NOT NULL,
    CONSTRAINT PK_MODELOSEQUIPOS PRIMARY KEY (ID_MODELO),
    CONSTRAINT UK_MODELOSEQUIPOS UNIQUE (NOMBRE)
);

CREATE TABLE MARCAS_MODELO
(
    ID_MARCA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE   VARCHAR(30) NOT NULL,
    CONSTRAINT PK_MARCASMODELOS PRIMARY KEY (ID_MARCA)
);

CREATE TABLE PERMISOS
(
    ID_PERMISO   NUMBER GENERATED ALWAYS AS IDENTITY,
    TIPO_PERMISO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_PERMISOS PRIMARY KEY (ID_PERMISO),
    CONSTRAINT UK_TIPO_PERMISOPERMISOS UNIQUE (TIPO_PERMISO)
);

CREATE TABLE PERFILES_PERMISOS
(
    ID_PERFIL  NUMBER,
    ID_PERMISO NUMBER NOT NULL,
    CONSTRAINT PK_PERFILESPERMISOS PRIMARY KEY (ID_PERFIL, ID_PERMISO)
);

CREATE TABLE USUARIOS_TELEFONOS
(
    ID_TELEFONO NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ID_USUARIO  NUMBER,
    NUMERO      VARCHAR(20)                         NOT NULL,
    CONSTRAINT PK_TELEFONO PRIMARY KEY (ID_TELEFONO)
);

CREATE TABLE PERFILES
(
    ID_PERFIL     NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_PERFIL VARCHAR(20)                  NOT NULL,
    ESTADO        VARCHAR(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_PERFILES PRIMARY KEY (ID_PERFIL),
    CONSTRAINT UK_NOMBREPERFILES UNIQUE (NOMBRE_PERFIL)
);

CREATE TABLE OPERACIONES
(
    ID_OPERACION     NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_OPERACION VARCHAR(30) NOT NULL,
    CONSTRAINT PK_OPERACIONES PRIMARY KEY (ID_OPERACION),
    CONSTRAINT UK_NOMBREOPERACIONES UNIQUE (NOMBRE_OPERACION)
);

CREATE TABLE AUDITORIAS
(
    ID_AUDITORIA NUMBER GENERATED ALWAYS AS IDENTITY,
    FECHA_HORA   DATE   NOT NULL,
    ID_USUARIO   NUMBER NOT NULL,
    ID_OPERACION NUMBER NOT NULL,
    CONSTRAINT PK_AUDITORIAS PRIMARY KEY (ID_AUDITORIA)
);


CREATE TABLE INSTITUCIONES
(
    ID_INSTITUCION NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE         VARCHAR(40) NOT NULL,
    CONSTRAINT PK_INSTITUCIONES PRIMARY KEY (ID_INSTITUCION)
);
CREATE TABLE UBICACIONES
(
    ID_UBICACION   NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE         VARCHAR(30)                  NOT NULL,
    SECTOR         VARCHAR(30),
    PISO           NUMBER,
    NUMERO         NUMBER,
    CAMA           NUMBER,
    ID_INSTITUCION NUMBER,
    ESTADO         VARCHAR(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_UBICACIONES PRIMARY KEY (ID_UBICACION)
);
CREATE TABLE BAJA_EQUIPOS
(
    ID_BAJA     NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO  NUMBER                       NOT NULL,
    ID_EQUIPO   NUMBER                       NOT NULL,
    RAZON       VARCHAR(30)                  NOT NULL,
    FECHA       DATE                         NOT NULL,
    ESTADO      VARCHAR(20) DEFAULT 'ACTIVO' NOT NULL,
    COMENTARIOS VARCHAR(100),
    CONSTRAINT PK_BAJAEQUIPOS PRIMARY KEY (ID_BAJA)
);

CREATE TABLE EQUIPOS_UBICACIONES
(
    ID_MOVIMIENTO NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_EQUIPO     NUMBER,
    ID_UBICACION  NUMBER,
    FECHA         DATE,
    USUARIO       NUMBER CONSTRAINT FK_EQUB_USUARIOS REFERENCES USUARIOS (ID_USUARIO),
    OBSERVACIONES VARCHAR(1000),
    CONSTRAINT PK_EQUIPOSUBICACIONES PRIMARY KEY (ID_MOVIMIENTO)
);

CREATE TABLE BAJA_UBICACIONES
(
    ID_BAJA      NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ID_USUARIO   NUMBER(38, 0),
    ID_UBICACION NUMBER(38, 0),
    RAZON        VARCHAR2(255),
    COMENTARIO   VARCHAR2(255),
    FECHA        DATE                                           NOT NULL,
    CONSTRAINT PK_BAJA_UBICACIONES PRIMARY KEY (ID_BAJA)
);

ALTER TABLE AUDITORIAS
    ADD CONSTRAINT FK_AUDITORIAS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
    ADD CONSTRAINT FK_AUDITORIAS_OPERACION FOREIGN KEY (ID_OPERACION) REFERENCES OPERACIONES (ID_OPERACION);

ALTER TABLE PERFILES_PERMISOS
    ADD CONSTRAINT FK_PERFILESPERMISOS_PERFILES FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES (ID_PERFIL)
    ADD CONSTRAINT FK_PERFILESPERMISOS_PERMISOS FOREIGN KEY (ID_PERMISO) REFERENCES PERMISOS (ID_PERMISO);

ALTER TABLE USUARIOS_TELEFONOS
    ADD CONSTRAINT FK_USUARIOSTELEFONOS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO);

ALTER TABLE EQUIPOS
    ADD CONSTRAINT FK_EQUIPOS_UBICACIONES FOREIGN KEY (ID_UBICACION) REFERENCES UBICACIONES (ID_UBICACION)
    ADD CONSTRAINT FK_EQUIPOS_TIPOSEQUIPOS FOREIGN KEY (ID_TIPO) REFERENCES TIPOS_EQUIPOS (ID_TIPO)
    ADD CONSTRAINT FK_EQUIPOS_PROVEEDORES FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES_EQUIPOS (ID_PROVEEDOR)
    ADD CONSTRAINT FK_EQUIPOS_PAISES FOREIGN KEY (ID_PAIS) REFERENCES PAISES (ID_PAIS)
    ADD CONSTRAINT FK_EQUIPOS_MODELOSEQUIPOS FOREIGN KEY (ID_MODELO) REFERENCES MODELOS_EQUIPOS (ID_MODELO);

ALTER TABLE INTERVENCIONES
    ADD CONSTRAINT FK_INTERVENCIONES_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
    ADD CONSTRAINT FK_INTERVENCIONES_TIPOSINTERVENCIONES FOREIGN KEY (ID_TIPO) REFERENCES TIPOS_INTERVENCIONES (ID_TIPO)
    ADD CONSTRAINT FK_INTERVENCIONES_EQUIPOS FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID_EQUIPO);

ALTER TABLE USUARIOS
    ADD CONSTRAINT FK_USUARIOS_PERFILES FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES (ID_PERFIL)
    ADD CONSTRAINT FK_USUARIOS_INSTITUCIONES FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCIONES (ID_INSTITUCION);

ALTER TABLE UBICACIONES
    ADD CONSTRAINT FK_UBICACIONES_INSTITUCIONES FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCIONES (ID_INSTITUCION);

ALTER TABLE BAJA_EQUIPOS
    ADD CONSTRAINT FK_BAJAEQUIPOS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
    ADD CONSTRAINT FK_BAJAEQUIPOS_EQUIPOS FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID_EQUIPO);

ALTER TABLE MODELOS_EQUIPOS
    ADD CONSTRAINT FK_MODELOSEQUIPOS_MARCASMODELOS FOREIGN KEY (ID_MARCA) REFERENCES MARCAS_MODELO (ID_MARCA);

ALTER TABLE EQUIPOS_UBICACIONES
    ADD CONSTRAINT FK_EQUB_EQUIPOS FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID_EQUIPO)
    ADD CONSTRAINT FK_EQUB_UBICACIONES FOREIGN KEY (ID_UBICACION) REFERENCES UBICACIONES (ID_UBICACION);

ALTER TABLE BAJA_UBICACIONES
    ADD CONSTRAINT FK_BAJA_UBICACIONES_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
    ADD CONSTRAINT FK_BAJA_UBICACIONES_UBICACIONES FOREIGN KEY (ID_UBICACION) REFERENCES UBICACIONES (ID_UBICACION);

-- Creacion de la base de datos con datos
-- Se crea la institucion
INSERT INTO INSTITUCIONES (NOMBRE)
VALUES ('CodigoCreativo');
-- Se crean los perfiles
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO)
VALUES ('Administrador', 'ACTIVO');
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO)
VALUES ('Aux administrativo', 'ACTIVO');
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO)
VALUES ('Ingeniero biomédico', 'ACTIVO');
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO)
VALUES ('Tecnico', 'ACTIVO');
-- Se crean los usuarios
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('52092449', 'Admin', 'Admin', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Administrador'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'admin@admin.com', 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-11-01');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('70102943', 'Marcelo', 'Puentes', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Aux administrativo'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'marcelop@admin.com', 'marcelo.puentes', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-01-01');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('35453656', 'Madgalena', 'Rivas', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Ingeniero biomédico'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'madgalena@admin.com', 'madgalena.rivas', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-02-02');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('6047909', 'Esteban', 'Paredes', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Tecnico'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'esteban@admin.com', 'esteban.paredes', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-03-03');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('45722005', 'Pedro', 'Artemis', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Administrador'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'pedro@admin.com', 'pedro.artemis', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-04-04');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('37647069', 'Ramon', 'Mitre', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Aux administrativo'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'ramon@admin.com', 'ramon.mitre', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-05-05');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('72940343', 'Alvaro', 'Salazar', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Ingeniero biomédico'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'alvaro@admin.com', 'alvaro.salazar', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-06-06');
--Se crean telefonos de usuarios
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'admin'), '095478654');
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'marcelo.puentes'), '098224558');
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'alvaro.salazar'), '099984521');
-- Se crean los tipos de equipos
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Desfribilador');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Monitor de signos');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Electroquirurjico');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Anestesiometro');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Rayos x');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Nebulizador');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Electrocardiógrafo');
-- Se crean las Marcas de equipos
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Welch Allyn');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Health o Meter');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Draguer');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Thomas');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Omron');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('EDAN');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Mindray');
-- Se crean los modelos de equipos
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Welch Allyn'), 'Kaspery');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Health o Meter'), 'Rowback');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Draguer'), '700G');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Thomas'), '007');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Omron'), 'NE-C801');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'EDAN'), 'M50');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'EDAN'), 'SE 301');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Mindray'), 'BeneHeart D3');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Mindray'), 'Wato EX 65');
-- Se crean los países
INSERT INTO PAISES (NOMBRE) VALUES ('Uruguay');
INSERT INTO PAISES (NOMBRE) VALUES ('Argentina');
INSERT INTO PAISES (NOMBRE) VALUES ('Brasil');
INSERT INTO PAISES (NOMBRE) VALUES ('Chile');
-- Se crean permisos
INSERT INTO PERMISOS (TIPO_PERMISO) VALUES ('Agregar');
INSERT INTO PERMISOS (TIPO_PERMISO) VALUES ('Borrar');
INSERT INTO PERMISOS (TIPO_PERMISO) VALUES ('Editar');
INSERT INTO PERMISOS (TIPO_PERMISO) VALUES ('Ver');
-- Se crean proveedores
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE) VALUES ('MedicTube');
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE) VALUES ('MoniVita');
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE) VALUES ('Desfribilados');
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE) VALUES ('Anestesic');
-- Se crean tipos de intervenciones
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Predictivo', 'ACTIVO');
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Correctivo', 'ACTIVO');
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Preventivo', 'ACTIVO');
-- Se crean ubicaciones
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Odontologia', 'Policlínico', 1, 2, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'INACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Obstreta', 'Policlínico', 2, 2, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Box Rapido', 'Emergencia', 1, 1, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Cirugia', 'CTI', 1, 2, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Limpieza', 'Emergencia', 1, 1, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Sala de espera', 'Emergencia', 1, 1, 1, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Cuidados intermedios', 'Internación', 3, 3, 2, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'INACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Cuarentena', 'Internación', 1, 2, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
-- Se crean las baja de ubicaciones
INSERT INTO BAJA_UBICACIONES (ID_USUARIO, ID_UBICACION, RAZON, COMENTARIO, FECHA) VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'admin'), (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Odontologia'), 'Cerrado por remodelacion', 'Cambio de piso', DATE '2023-11-27');
INSERT INTO BAJA_UBICACIONES (ID_USUARIO, ID_UBICACION, RAZON, COMENTARIO, FECHA) VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'admin'), (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Cuidados intermedios'), 'Cambio de nombre', 'ninguno', DATE '2023-12-17');
-- Se crean Equipos
INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1001', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Box Rapido'), '123355533', 'Tensiometro', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Monitor de signos'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'MoniVita'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE 'Rowback'), 'https://i.ibb.co/X26FksG/tensiometro.jpg', DATE '2023-11-01');
INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1002', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Cirugia'), '12255577', 'Anestesiometro cirugia', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Anestesiometro'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'Anestesic'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE '700G'), 'https://i.ibb.co/Ht5DfKp/mgoitd09.png', DATE '2020-11-11');
INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1003', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Cuarentena'), '654456778', 'Nebulizador', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Nebulizador'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'MedicTube'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE 'NE-C801'), 'https://i.ibb.co/LRRHW2s/nebulizador-omron-NE-C801-1-977x1024-1.png', DATE '2020-11-08');
INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1004', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Cirugia'), '544568786', 'Desfribilador CTI', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Desfribilador'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'Desfribilados'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE 'BeneHeart D3'), 'https://i.ibb.co/WVpb5s4/beneheath-d3-977x1024-1.png', DATE '2010-10-05');
INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1005', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Cirugia'), '454644678', 'Cardiografo', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Electrocardiógrafo'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'MedicTube'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE 'SE 301'), 'https://i.ibb.co/qFhSVVb/edan-se-301-1-1.png', DATE '2017-03-10');
INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1006', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Box Rapido'), '45875517', 'Anestesiometro emergencia', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Anestesiometro'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'Anestesic'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE 'Wato EX 65'), 'https://i.ibb.co/g6YL0F9/maquina-de-anestesia-mindray-wato-ex-65-1-977x1024-1.png', DATE '2019-05-20');
-- Se crean las intervenciones
INSERT INTO INTERVENCIONES (ID_USUARIO, ID_TIPO, ID_EQUIPO, MOTIVO, FECHA_HORA, COMENTARIOS)
VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'admin'), (SELECT ID_TIPO FROM TIPOS_INTERVENCIONES WHERE NOMBRE_TIPO LIKE 'Correctivo'), (SELECT ID_EQUIPO FROM EQUIPOS WHERE NOMBRE LIKE 'Tensiometro'), 'No encendia', TIMESTAMP '2023-11-27 18:30:00', 'Faltaban pilas');
INSERT INTO INTERVENCIONES (ID_USUARIO, ID_TIPO, ID_EQUIPO, MOTIVO, FECHA_HORA, COMENTARIOS)
VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'admin'), (SELECT ID_TIPO FROM TIPOS_INTERVENCIONES WHERE NOMBRE_TIPO LIKE 'Preventivo'), (SELECT ID_EQUIPO FROM EQUIPOS WHERE NOMBRE LIKE 'Anestesiometro emergencia'), 'Limpiar conductos', TIMESTAMP '2023-11-30 17:00:00', 'Se debe limpiar los conductos por donde viaja la medicacion al paciente.');
-- Se crean los permisos de los perfiles
INSERT INTO PERFILES_PERMISOS (ID_PERFIL, ID_PERMISO) VALUES ((SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Administrador'), (SELECT ID_PERMISO FROM PERMISOS WHERE TIPO_PERMISO LIKE 'Ver'));
INSERT INTO PERFILES_PERMISOS (ID_PERFIL, ID_PERMISO) VALUES ((SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Administrador'), (SELECT ID_PERMISO FROM PERMISOS WHERE TIPO_PERMISO LIKE 'Agregar'));

