services:
  nodejs:
    image: node:latest
    container_name: nodejs
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - dev-network

  wildfly:
    build:
      context: .
    container_name: wildfly
    volumes:
      - ./backend:/opt/jboss/wildfly/standalone/deployments
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - dev-network
    environment:
      - MGMT_USER=${WILDFLY_USERNAME}
      - MGMT_PASS=${WILDFLY_PASSWORD}


  oracle-db:
    image: gvenzl/oracle-xe:18.4.0
    container_name: oracle-db
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "${DB_PORT}:1521"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
